name: Docker Image CI
on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "TAG=$(date +%s)" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - run: |
          docker build . --file Dockerfile --tag ghcr.io/krupanszkymarcell/rams:$TAG --tag ghcr.io/krupanszkymarcell/rams:latest
          docker login ghcr.io -u krupanszkymarcell -p ${{secrets.TOKEN}}
          docker push ghcr.io/krupanszkymarcell/rams:$TAG
          docker push ghcr.io/krupanszkymarcell/rams:latest